import { createRoot, hydrateRoot } from "react-dom/client";
import App from "./App";
import "./index.css";

declare global {
  interface Window {
    openSallaSecretsCheckout?: () => void;
  } 
}

const rootElement = document.getElementById("root")!;

// Pages generated by the prerender step already contain full markup —
// hydrate them instead of wiping and re-rendering from an empty div.
// Falls back to a normal client render in dev (vite dev serves an empty
// #root) or for any route the prerender step doesn't cover.
if (rootElement.hasChildNodes()) {
  hydrateRoot(rootElement, <App />);
} else {
  createRoot(rootElement).render(<App />);
}
